name: Node.js Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci  # plus fiable pour CI que npm install

      - name: Run ESLint
        run: npx eslint .  # utilise npx pour contourner les problèmes de permission

      - name: Run unit tests
        run: npm test --detectOpenHandles  # optionnel pour détecter les ressources ouvertes

  docker-build:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t docker-ci-node .
          docker images